#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2017

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1

# Tests
test: off

#---------------------------------#
#  Notifications                  #
#---------------------------------#
notifications:
- provider: Email
  to:
  - r.mirandaterra@gmail.com
  subject: NesZord Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
