#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017

# environment variables
environment:
  COVERALLS_REPO_TOKEN:
    secure: DDa8QDqRhBXiOKSOiWU3iVZQBWHwjp2PIrPHM+8M94Wnk30bpXqL+2k7bZsTMugZ

#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Target AppVeyor

# Tests
test: off

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
- provider: Email
  to:
  - r.mirandaterra@gmail.com
  subject: NesZord Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
 